# Publishes a tag/branch to Composer Packages of the current project
publish:
  image: curlimages/curl:latest
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_ID' # Ensures the job does not run in MR pipelines
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /^development\/.*$/ && $CI_PIPELINE_SOURCE == "push"' # Runs only on push after MR merge
  script:
    - TAG_NAME=$(echo $CI_COMMIT_BRANCH | sed 's/^development\///')-dev
    - echo "Tag to create: $TAG_NAME"
    - git config --global user.email "ci@example.com"  # Set user email for git tagging
    - git config --global user.name "GitLab CI"  # Set user name for git tagging
    - git tag $TAG_NAME  # Create the tag locally
    - git push origin $TAG_NAME  # Push the tag to the remote repository
    - 'curl --fail-with-body --header "Job-Token: $CI_JOB_TOKEN" --data tag=$TAG_NAME "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
