publish:
  image: node:latest
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v/ && $CI_COMMIT_TAG !~ /dev/'
  before_script:
    - apt-get update && apt-get install -y jq
  script:
    # Extract version from tag (remove 'v' prefix if present)
    - VERSION=$(echo "$CI_COMMIT_TAG" | sed 's/^v//')
    - 'echo "Extracted version: $VERSION"'

    # Update composer.json with the new version
    - jq --arg version "$VERSION" '.version = $version' composer.json > composer.tmp.json
    - mv composer.tmp.json composer.json
    - 'git config --global user.email "ci@example.com"'  # Set user email for git tagging
    - 'git config --global user.name "GitLab CI"'  # Set user name for git tagging
    - 'git push https://oauth2:${CI_ACCESS_TOKEN}@${CI_SERVER_HOST}/$CI_PROJECT_PATH.git' # Use CI_JOB_TOKEN to authenticate
    - 'curl --fail-with-body --header "Job-Token: $CI_JOB_TOKEN" --data tag=$TAG_NAME "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
