test:
  stage: test
  image: composer:latest
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /internal/' # Only for external GitLab URLs
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - when: never
  variables:
    # Xdebug configuration
    XDEBUG_MODE: coverage
  before_script:
    - echo xdebug.mode=coverage >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - composer install
    - ./vendor/bin/testbench vendor:publish --tag="filament-package_ffhs_approvals-migrations"
    - ./vendor/bin/testbench workbench:build
  script:
    - php vendor/bin/pest --coverage
  coverage: /Total:\s*([^%]+)/

