build:vendors:
  stage: build
  only:
    refs:
      - merge_requests
      - push
  cache:
    key:
      files:
        - composer.lock
    policy: pull-push
  image: composer:2
  script:
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - ./vendor/bin/testbench vendor:publish --tag="filament-package_ffhs_approvals-migrations"
    - ./vendor/bin/testbench workbench:build


tests:
  stage: test
  only:
    refs:
      - merge_requests
  #  rules:
  #    - if: '$CI_COMMIT_BRANCH =~ /internal/' # Only for external GitLab URLs
  #      when: never
  #    - if: $CI_MERGE_REQUEST_ID
  #      when: always
  #    - when: never
  cache:
    key:
      files:
        - composer.lock
    policy: pull
  image: php:8.2
  script:
    - ./vendor/bin/pest --ci --coverage
  coverage: /Total:\s*([^%]+)/

#test:
#  stage: test
#  image: composer:latest
#  rules:
#    - if: '$CI_COMMIT_BRANCH =~ /internal/' # Only for external GitLab URLs
#      when: never
#    - if: $CI_MERGE_REQUEST_ID
#      when: always
#    - when: never
#  variables:
#    # Xdebug configuration
#    XDEBUG_MODE: coverage
#  before_script:
#    - echo xdebug.mode=coverage >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#    - composer install
#  script:
#    - php vendor/bin/pest --coverage
#  coverage: /Total:\s*([^%]+)/

